# Generated by Django 5.2.1 on 2026-09-12 21:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mal_id', models.PositiveIntegerField(db_index=True, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('poster', models.URLField(blank=True, null=True, verbose_name='Обложка')),
                ('episodes', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Количество эпизодов')),
                ('genres', models.ManyToManyField(related_name='genre', to='main.genre')),
            ],
        ),
        migrations.CreateModel(
            name='UserAnime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_note', models.TextField(blank=True, null=True, verbose_name='Заметка пользователя')),
                ('user_rate', models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True, validators=[django.core.validators.MinValueValidator(Decimal('1.0')), django.core.validators.MaxValueValidator(Decimal('10.0'))], verbose_name='Оценка пользователя')),
                ('user_fav_character', models.CharField(blank=True, max_length=255, null=True, verbose_name='Любимый персонаж')),
                ('user_status', models.CharField(choices=[('WW', 'Want to watch'), ('PR', 'Watching'), ('WD', 'Watched'), ('DR', 'Dropped')], default='WW', max_length=2)),
                ('started_at', models.DateField(blank=True, null=True)),
                ('finished_at', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anime', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='user_entries', to='main.anime')),
            ],
        ),
    ]
