server {
    listen 80;

    # Запросы к API — проксируем в Django
    location /api/ {
        proxy_pass http://anitrack:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Всё остальное — отдаём React
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}