server {
    listen 80;

    # ── API → Django ──────────────────────────────────────
    location /api/ {
        proxy_pass http://anitrack:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ── Django Admin → Django ─────────────────────────────
    location /admin/ {
        proxy_pass http://anitrack:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # ── Статика Django (admin CSS/JS) ─────────────────────
    location /static/ {
        alias /vol/static/;
    }

    # ── Media (аватары пользователей) ─────────────────────
    location /media/ {
        alias /vol/media/;
    }

    # ── Всё остальное → React ─────────────────────────────
    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}